#
# Travis CI configuration file for codedoc.
#

language: c

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Dgplt9bAs7liVAedk7vkYVpaVQrctvftfrzwvbQxq3MqLI/nSNaxRUOdY65rHwWp8iK4iMoBJgCIQntwLq7AyahgZWL+v7ErBIEhfLJUtTe8hwUhzJNQsr9NMTFqmWP6BPNyf7a4UcDrHEUUvvMS/yltdXMEYZz80vgakXUSgHjtpHlh/mnFm77RvQ4HDBE6Vv4TWEJtn3lmqZUrSDa+ZT3dgX+IlmwkdkfY7urFgbZmGZnPqQZnRDUq8bNlT+y6XK21vV9zNXi4uUNIeGjT2nT8seB2ukFa2eO53nsm7ldO3TtdkXV1b6MSbjiOP0u+/RIWjzTCRFZ3Zjk4AyJ8zrgFtPGCwSRczUDxDU9xdjN1NgYWIlLUFgXowZPWN39TizoA58TjSby6ewRdLH1esFTkAxgcZSIpYJua6AUq0ZaHxqfaK8KXA/dr6DKxd6XE0M8EqoJ3r5WDNJLbynrdHisUWRDvVEb3L5otou43Uwddm288mTV5NyZUsaT0cPOqtqgKDT69SnKW6/rfvxIx24a370o3hElS8x5sSiENeaQKkBA5GaTEiDJrIGDwDcWOba1TjcgPYIPdCUfkcM/w+8wVAfiyh+dIjgC/LK0FhRVLki2HymgmKdnSLy/luy+At3dlGkwl/uC4+WAan/KYav+P5iUX7HNYm+ZiXx+ABxY="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

jobs:
  include:
    # Linux-specific build stuff
    - os: linux
      dist: focal
      virt: vm
      env:
        - ASAN_OPTIONS=leak_check_at_exit=false
      script: make sanitizer && make test && make cppcheck
      addons:
        apt:
          packages: [cppcheck, libmxml-dev]
        addons:
          coverity_scan:
            project:
              name: "michaelrsweet/codedoc"
              description: "A Code Documentation Utility"
            notification_email: msweet@msweet.org
            build_command_prepend: "make clean"
            build_command: "make"
            branch_pattern: master

    # macOS-specific build stuff
    - os: osx
      osx_image: xcode12.2
      script: make sanitizer && make test
      addons:
        homebrew:
          packages: [libmxml]
          update: true

notifications:
  email:
    recipients:
      - msweet@msweet.org
